using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using Scanner.Core;
namespace Scanner.Desktop;
public sealed class MaterialsWindow:Window
{
 public record ViewSettings(string City,int Tier,int Enchantment,string Search,string Group,bool Missing);
 public sealed class PriceRow{public string Updated{get;set;}="";public string ItemId{get;init;}="";public string Name{get;init;}="";public string Tier{get;init;}="";public string Enchantment{get;init;}="";public string Price{get;set;}="";public string Original{get;set;}="";}
 readonly ManualPriceStore store;readonly string server;readonly Action changed;readonly List<MaterialEntry> catalog;
 readonly ComboBox group=new(){Width=180};readonly CheckBox missing=new(){Content="Missing prices only",Foreground=System.Windows.Media.Brushes.White,Margin=new Thickness(0,12,0,12)};string selectedGroup="All materials";bool selectedMissing;
 readonly ComboBox city=new(){Width=180},tier=new(){Width=130},enchantment=new(){Width=150};readonly TextBox search=new(){Width=240};readonly DataGrid grid=new();readonly TextBlock status=new(){TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,12,0,0)};
 List<PriceRow> rows=[];string selectedCity;int selectedTier=0,selectedEnchantment=-1;string selectedSearch="";bool ready;
 public MaterialsWindow(IEnumerable<Recipe> recipes,ManualPriceStore store,string server,string initialCity,Action changed)
 {
  this.store=store;this.server=server;this.changed=changed;selectedCity=initialCity;catalog=MaterialCatalog.FromRecipes(recipes);
  Style=(Style)FindResource(typeof(Window));Title="Materials · "+server;Width=1220;Height=760;MinWidth=900;MinHeight=550;WindowStartupLocation=WindowStartupLocation.CenterOwner;
  var body=new DockPanel{Margin=new Thickness(24),Background=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(14,22,32))};Content=body;
  var top=new StackPanel();DockPanel.SetDock(top,Dock.Top);body.Children.Add(top);
  top.Children.Add(new TextBlock{Text="Materials · "+server,FontSize=25,FontWeight=FontWeights.SemiBold});
  top.Children.Add(new TextBlock{Text="Edit saved unit prices for this server and city. Crafting artifacts are excluded. Blank prices clear a saved value. Changes save with Save prices, when changing filters, or when closing.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,10,0,16)});
  var filters=new WrapPanel{Margin=new Thickness(0,0,0,16)};top.Children.Add(filters);
  void FilterBox(string label,Control control){var panel=new StackPanel{Margin=new Thickness(0,0,16,0)};panel.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,0,0,6)});panel.Children.Add(control);filters.Children.Add(panel);System.Windows.Automation.AutomationProperties.SetName(control,label);}
  FilterBox("Material type",group);FilterBox("City",city);FilterBox("Tier",tier);FilterBox("Enchantment",enchantment);FilterBox("Find material",search);
  group.ItemsSource=new[]{"All materials","Raw Resources","Refined Resources","Other Ingredients"};group.SelectedIndex=0;top.Children.Add(missing);
  city.ItemsSource=MarketClient.Cities;city.SelectedItem=initialCity;tier.ItemsSource=new[]{"All tiers","T1","T2","T3","T4","T5","T6","T7","T8"};tier.SelectedIndex=0;enchantment.ItemsSource=new[]{"All enchantments",".0 — Normal",".1",".2",".3",".4"};enchantment.SelectedIndex=0;
  var bottom=new StackPanel();DockPanel.SetDock(bottom,Dock.Bottom);body.Children.Add(bottom);var save=new Button{Content="Save prices",HorizontalAlignment=HorizontalAlignment.Left,Margin=new Thickness(0,16,0,0)};save.Click+=(_,_)=>{if(TrySave())LoadRows();};bottom.Children.Add(save);bottom.Children.Add(status);
  grid.FrozenColumnCount=1;grid.CanUserReorderColumns=false;grid.SelectionUnit=DataGridSelectionUnit.Cell;grid.Columns.Add(new DataGridTextColumn{Header="Material",Binding=new Binding("Name"),IsReadOnly=true,MinWidth=360,Width=new DataGridLength(1,DataGridLengthUnitType.Star)});grid.Columns.Add(new DataGridTextColumn{Header="Tier",Binding=new Binding("Tier"),IsReadOnly=true,Width=80});grid.Columns.Add(new DataGridTextColumn{Header="Enchantment",Binding=new Binding("Enchantment"),IsReadOnly=true,Width=120});grid.Columns.Add(new DataGridTextColumn{Header="Saved unit price · silver",Binding=new Binding("Price"){UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged},Width=230});grid.Columns.Add(new DataGridTextColumn{Header="Last updated",Binding=new Binding("Updated"),IsReadOnly=true,Width=165});body.Children.Add(grid);
  RestoreView();group.SelectionChanged+=(_,_)=>FiltersChanged();missing.Checked+=(_,_)=>FiltersChanged();missing.Unchecked+=(_,_)=>FiltersChanged();city.SelectionChanged+=(_,_)=>FiltersChanged();tier.SelectionChanged+=(_,_)=>FiltersChanged();enchantment.SelectionChanged+=(_,_)=>FiltersChanged();search.TextChanged+=(_,_)=>FiltersChanged();Closing+=(_,e)=>{if(!TrySave())e.Cancel=true;else SaveView();};ready=true;LoadRows();
 }
 void FiltersChanged(){if(!ready)return;if(!TrySave()){ready=false;city.SelectedItem=selectedCity;tier.SelectedIndex=selectedTier;enchantment.SelectedIndex=selectedEnchantment+1;search.Text=selectedSearch;group.SelectedItem=selectedGroup;missing.IsChecked=selectedMissing;ready=true;return;}selectedCity=(string)city.SelectedItem;selectedTier=tier.SelectedIndex;selectedEnchantment=enchantment.SelectedIndex-1;selectedSearch=search.Text;selectedGroup=(string)group.SelectedItem;selectedMissing=missing.IsChecked==true;SaveView();LoadRows();}
 void LoadRows(){var entries=MaterialCatalog.Filter(catalog,selectedTier,selectedEnchantment,selectedSearch).Where(m=>selectedGroup=="All materials"||MaterialCatalog.GroupOf(m.ItemId)==selectedGroup).ToList();var prices=store.Get(server,selectedCity,entries.Select(m=>m.ItemId));rows=entries.Where(m=>!selectedMissing||!prices.ContainsKey(m.ItemId)).Select(m=>{var value=prices.TryGetValue(m.ItemId,out var p)?p.ToString(CultureInfo.CurrentCulture):"";return new PriceRow{ItemId=m.ItemId,Name=m.Name,Tier=m.Tier==0?"—":"T"+m.Tier,Enchantment="."+m.Enchantment,Price=value,Original=value,Updated=value==""?"Not priced":store.UpdatedAt(server,selectedCity,m.ItemId)?.LocalDateTime.ToString("g")??"Unknown (older price)"};}).ToList();grid.ItemsSource=rows;status.Text=$"{rows.Count:N0} materials · {server} / {selectedCity}. Edit a price, then save. Existing crafting sessions keep their original price snapshots.";}
 void RestoreView(){if(!System.IO.File.Exists(store.PreferencesPath))return;try{var v=DataFiles.Read<ViewSettings>(store.PreferencesPath);if(!MarketClient.Cities.Contains(v.City)||v.Tier<0||v.Tier>8||v.Enchantment< -1||v.Enchantment>4||!group.Items.Contains(v.Group))return;selectedCity=v.City;selectedTier=v.Tier;selectedEnchantment=v.Enchantment;selectedSearch=v.Search??"";selectedGroup=v.Group;selectedMissing=v.Missing;city.SelectedItem=selectedCity;tier.SelectedIndex=selectedTier;enchantment.SelectedIndex=selectedEnchantment+1;search.Text=selectedSearch;group.SelectedItem=selectedGroup;missing.IsChecked=selectedMissing;}catch{status.Text="Could not restore filters; using defaults.";}}
 void SaveView(){try{DataFiles.Save(store.PreferencesPath,new ViewSettings(selectedCity,selectedTier,selectedEnchantment,selectedSearch,selectedGroup,selectedMissing));}catch(Exception ex){status.Text="Could not save filters: "+ex.Message;}}
 bool TrySave(){try{SaveRows();return true;}catch(Exception ex){status.Text="Prices were not saved: "+ex.Message;return false;}}
 void SaveRows(){if(!grid.CommitEdit(DataGridEditingUnit.Cell,true)||!grid.CommitEdit(DataGridEditingUnit.Row,true))throw new ArgumentException("Finish editing the current price.");var dirty=rows.Where(r=>r.Price!=r.Original).ToList();if(dirty.Count==0)return;var values=new Dictionary<string,decimal>();foreach(var row in dirty){if(string.IsNullOrWhiteSpace(row.Price))continue;if(!decimal.TryParse(row.Price,NumberStyles.AllowDecimalPoint|NumberStyles.AllowLeadingWhite|NumberStyles.AllowTrailingWhite,CultureInfo.CurrentCulture,out var value)||value<=0||value>1000000000000m)throw new ArgumentException("Enter a positive price without thousands separators for "+row.Name+", or leave it blank to clear.");values[row.ItemId]=value;}store.Save(server,selectedCity,dirty.Select(r=>r.ItemId),values);foreach(var row in dirty)row.Original=row.Price;changed();status.Text=$"Saved {dirty.Count} price change(s) for {server} / {selectedCity}. Main-window totals refreshed.";}
 public void SmokeTest(){group.SelectedItem="Refined Resources";missing.IsChecked=false;search.Text="";city.SelectedItem="Martlock";tier.SelectedIndex=5;enchantment.SelectedIndex=4;var plank=rows.Single(r=>r.ItemId=="T5_PLANKS_LEVEL3@3");plank.Price="1234";SaveRows();if(store.Get(server,"Martlock",[plank.ItemId])[plank.ItemId]!=1234)throw new Exception("Material price save failed");tier.SelectedIndex=4;tier.SelectedIndex=5;if(rows.Single(r=>r.ItemId==plank.ItemId).Price!="1234")throw new Exception("Material price reload failed");if(store.UpdatedAt(server,"Martlock",plank.ItemId)==null)throw new Exception("Price date missing");missing.IsChecked=true;if(rows.Any(r=>r.ItemId==plank.ItemId))throw new Exception("Missing filter failed");missing.IsChecked=false;var savedView=DataFiles.Read<ViewSettings>(store.PreferencesPath);if(savedView.City!="Martlock"||savedView.Tier!=5||savedView.Enchantment!=3||savedView.Group!="Refined Resources"||savedView.Missing)throw new Exception("Filters did not persist");}
}



