<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>AlbionScanner</AssemblyName><Version>4.5.0</Version><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Scanner.Core/Scanner.Core.csproj"/><Content Include="../../config/*.json" Link="config/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true"/></ItemGroup>
</Project>















